# System Under Test environment configuration for RGW custom deployment test config that can be used for simple exploration testing.
globals:
  - ceph-cluster:
      name: ceph

      node1:
        disk-size: 5
        no-of-volumes: 3
        role:
          - _admin
          - installer
          - mgr
          - mon
          - osd

      node2:
        disk-size: 5
        no-of-volumes: 3
        role:
          - mgr
          - mon
          - osd
          - rgw

      node3:
        disk-size: 5
        no-of-volumes: 3
        role:
          - mon
          - osd
          - rgw

      node4:
        disk-size: 5
        no-of-volumes: 3
        role:
          - osd
          - rgw

      node5:
        role:
          - client
